### Creating Dataframe

In [23]:
import numpy as np
import pandas as pd

In [24]:
student_data = [
    [100, 90, 10, 'tushar'],
    [90, 80, 7, 'ram'],
    [110, 95, 14, 'laksham'],
    [120, 97, 30, 'veer'],
]
student_data

[[100, 90, 10, 'tushar'],
 [90, 80, 7, 'ram'],
 [110, 95, 14, 'laksham'],
 [120, 97, 30, 'veer']]

In [25]:
# using list
student = pd.DataFrame(student_data,columns=['iq','marks','package', 'name'])
print(type(student))
student

<class 'pandas.core.frame.DataFrame'>

    iq  marks  package     name
0  100     90       10   tushar
1   90     80        7      ram
2  110     95       14  laksham
3  120     97       30     veer

In [26]:
# using read_csv()
movies = pd.read_csv('../datasets/movies.csv')
type(movies)
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
35071,152579,Lagaan (2001),Bollywood|Period|Drama|Sports|Comedy|Romance
35072,152580,Hum Aapke Hain Koun (1994),Bollywood|Drama|Musical|Comedy|Family
35073,152581,Khalnayak (1993),Bollywood|Crime|Action
35074,152583,Darr (1993),Bollywood|Thriller
35075,152584,Beta (1992),Bollywood|Drama

In [27]:
ipl = pd.read_csv('../datasets/ipl_matches_2.csv')
ipl

,team1,team2,match_date,toss_winner,toss_decision,winner,player_of_match,venue,city,team1_players,team2_players,season,match_number,match_type,result,result_margin,target_runs,target_overs,super_over
0,Royal Challengers Bangalore,Kolkata Knight Riders,2008-04-18,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,M Chinnaswamy Stadium,Bangalore,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",1,1,League,runs,140.0,223.0,20.0,N
1,Kings XI Punjab,Chennai Super Kings,2008-04-19,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",1,2,League,runs,33.0,241.0,20.0,N
2,Delhi Daredevils,Rajasthan Royals,2008-04-19,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,Feroz Shah Kotla,Delhi,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",1,3,League,wickets,9.0,130.0,20.0,N
3,Mumbai Indians,Royal Challengers Bangalore,2008-04-20,Mumbai Indians,bat,Royal Challengers Bangalore,MV Boucher,Wankhede Stadium,Mumbai,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",1,4,League,wickets,5.0,166.0,20.0,N
4,Kolkata Knight Riders,Deccan Chargers,2008-04-20,Deccan Chargers,bat,Kolkata Knight Riders,DJ Hussey,Eden Gardens,Kolkata,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",1,5,League,wickets,5.0,111.0,20.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,Lucknow Super Giants,Royal Challengers Bengaluru,2025-05-27,Royal Challengers Bengaluru,field,Royal Challengers Bengaluru,JM Sharma,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,"Akash Singh, MR Marsh, MP Breetzke, RR Pant, N...","Suyash Sharma, PD Salt, V Kohli, RM Patidar, L...",18,70,League,wickets,6.0,228.0,20.0,N
1165,Punjab Kings,Royal Challengers Bengaluru,2025-05-29,Royal Challengers Bengaluru,field,Royal Challengers Bengaluru,Suyash Sharma,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,"Priyansh Arya, P Simran Singh, JP Inglis, SS I...","Suyash Sharma, PD Salt, V Kohli, MA Agarwal, R...",18,71,Qualifier 1,wickets,8.0,102.0,20.0,N
1166,Mumbai Indians,Gujarat Titans,2025-05-30,Mumbai Indians,bat,Mumbai Indians,RG Sharma,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,"Ashwani Kumar, RG Sharma, JM Bairstow, SA Yada...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,...",18,72,Eliminator,runs,20.0,229.0,20.0,N
1167,Mumbai Indians,Punjab Kings,2025-06-01,Punjab Kings,field,Punjab Kings,SS Iyer,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,"Ashwani Kumar, RG Sharma, JM Bairstow, Tilak V...","YS Chahal, Priyansh Arya, P Simran Singh, JP I...",18,73,Qualifier 2,wickets,5.0,204.0,20.0,N
1168,Royal Challengers Bengaluru,Punjab Kings,2025-06-03,Punjab Kings,field,Royal Challengers Bengaluru,KH Pandya,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,"Suyash Sharma, PD Salt, V Kohli, MA Agarwal, R...","YS Chahal, Priyansh Arya, P Simran Singh, JP I...",18,74,Final,runs,6.0,191.0,20.0,N

### Dataframe Methods and Attributes

In [28]:
# shapes
print(movies.shape)
print(ipl.shape)

(35076, 3)
(1169, 19)

In [29]:
# dtype
movies.dtypes

movieId     int64
title      object
genres     object
dtype: object

In [30]:
# index
movies.index

RangeIndex(start=0, stop=35076, step=1)

In [31]:
# column
print(movies.columns)
print(ipl.columns)
print(student.columns)

Index(['movieId', 'title', 'genres'], dtype='object')
Index(['team1', 'team2', 'match_date', 'toss_winner', 'toss_decision',
       'winner', 'player_of_match', 'venue', 'city', 'team1_players',
       'team2_players', 'season', 'match_number', 'match_type', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over'],
      dtype='object')
Index(['iq', 'marks', 'package', 'name'], dtype='object')

In [32]:
# values
# print(student.values)
print(movies.values)
# print(ipl.values)

[[1 'Toy Story (1995)' 'Adventure|Animation|Children|Comedy|Fantasy']
 [2 'Jumanji (1995)' 'Adventure|Children|Fantasy']
 [3 'Grumpier Old Men (1995)' 'Comedy|Romance']
 ...
 [152581 'Khalnayak (1993)' 'Bollywood|Crime|Action']
 [152583 'Darr (1993)' 'Bollywood|Thriller']
 [152584 'Beta (1992)' 'Bollywood|Drama']]

In [33]:
# head and tail
# movies.head(5)
movies.tail(5)

,movieId,title,genres
35071,152579,Lagaan (2001),Bollywood|Period|Drama|Sports|Comedy|Romance
35072,152580,Hum Aapke Hain Koun (1994),Bollywood|Drama|Musical|Comedy|Family
35073,152581,Khalnayak (1993),Bollywood|Crime|Action
35074,152583,Darr (1993),Bollywood|Thriller
35075,152584,Beta (1992),Bollywood|Drama

In [34]:
# sample
movies.sample()

,movieId,title,genres
20578,100463,Quackser Fortune Has a Cousin in the Bronx (1970),Comedy|Drama|Romance

In [35]:
# info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35076 entries, 0 to 35075
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  35076 non-null  int64
 1   title    35076 non-null  object
 2   genres   35076 non-null  object
dtypes: int64(1), object(2)
memory usage: 822.2+ KB

In [36]:
# describe
ipl.describe()

            season  match_number  result_margin  target_runs  target_overs
count  1169.000000   1169.000000    1146.000000  1163.000000   1163.000000
mean      9.687767     33.359281      17.364747   167.253654     19.768014
std       5.253100     19.430749      21.919255    34.222771      1.542583
min       1.000000      1.000000       1.000000    43.000000      5.000000
25%       5.000000     17.000000       6.000000   147.000000     20.000000
50%      10.000000     33.000000       8.000000   167.000000     20.000000
75%      15.000000     49.000000      20.000000   188.000000     20.000000
max      18.000000     76.000000     146.000000   288.000000     20.000000

In [37]:
# isnull
ipl.isnull().sum()

team1               0
team2               0
match_date          0
toss_winner         0
toss_decision       0
winner             23
player_of_match     0
venue               0
city               51
team1_players       0
team2_players       0
season              0
match_number        0
match_type          0
result              0
result_margin      23
target_runs         6
target_overs        6
super_over          0
dtype: int64

In [38]:
# duplicate
ipl.duplicated().sum()

0

In [39]:
# rename
student

    iq  marks  package     name
0  100     90       10   tushar
1   90     80        7      ram
2  110     95       14  laksham
3  120     97       30     veer

In [40]:
student.rename(columns={'package':'lpa'}, inplace=True)
student # rename is not do permanet change on dataframe, if you want than inplace=True do this.

    iq  marks  lpa     name
0  100     90   10   tushar
1   90     80    7      ram
2  110     95   14  laksham
3  120     97   30     veer

### Math Methods

In [41]:
# sum -> axis arguments
print(student)
student.sum(axis=0)

    iq  marks  lpa     name
0  100     90   10   tushar
1   90     80    7      ram
2  110     95   14  laksham
3  120     97   30     veer

iq                        420
marks                     362
lpa                        61
name     tusharramlakshamveer
dtype: object

In [42]:
student.mean(axis=0)

TypeError: Could not convert ['tusharramlakshamveer'] to numeric

In [ ]:
student.min(axis=0)

iq       90
marks    80
lpa       7
dtype: int64

In [ ]:
student.var(axis=0)

iq       166.666667
marks     57.666667
lpa      104.916667
dtype: float64

In [ ]:
# column
student['lpa']

0    10
1     7
2    14
3    30
Name: lpa, dtype: int64

In [ ]:
# multiple column
print(ipl.columns)
ipl[['team1','team2','winner','match_date']]

Index(['team1', 'team2', 'match_date', 'toss_winner', 'toss_decision',
       'winner', 'player_of_match', 'venue', 'city', 'team1_players',
       'team2_players', 'season', 'match_number', 'match_type', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over'],
      dtype='object')

,team1,team2,winner,match_date
0,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,2008-04-18
1,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,2008-04-19
2,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,2008-04-19
3,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,2008-04-20
4,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,2008-04-20
...,...,...,...,...
1164,Lucknow Super Giants,Royal Challengers Bengaluru,Royal Challengers Bengaluru,2025-05-27
1165,Punjab Kings,Royal Challengers Bengaluru,Royal Challengers Bengaluru,2025-05-29
1166,Mumbai Indians,Gujarat Titans,Mumbai Indians,2025-05-30
1167,Mumbai Indians,Punjab Kings,Punjab Kings,2025-06-01
1168,Royal Challengers Bengaluru,Punjab Kings,Royal Challengers Bengaluru,2025-06-03

In [60]:
student.set_index('name', inplace=True)
# student

### Selecting rows from a DataFrame
- iloc - searches using index position
- loc - searches using index labels

In [61]:
student

          iq  marks  lpa
name
tushar   100     90   10
ram       90     80    7
laksham  110     95   14
veer     120     97   30

In [62]:
# single row
movies.iloc[0]

movieId                                              1
title                                 Toy Story (1995)
genres     Adventure|Animation|Children|Comedy|Fantasy
Name: 0, dtype: object

In [63]:
# multiple rows
movies.iloc[:5]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [64]:
# fancy indexing
movies.iloc[[0,1]]

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1        2    Jumanji (1995)                   Adventure|Children|Fantasy

In [67]:
print(student)

          iq  marks  lpa
name
tushar   100     90   10
ram       90     80    7
laksham  110     95   14
veer     120     97   30

In [68]:
# loc
student.loc['tushar']

iq       100
marks     90
lpa       10
Name: tushar, dtype: int64